21:26:12.020 - My_app - INFO - Connected to MySQL by user (main.py:67)
21:26:12.020 - My_app - INFO - Current user is user (main.py:167)
21:26:16.020 - My_app - ERROR - Dialogue window already opened (main.py:174)
21:26:16.020 - My_app - ERROR - Dialogue window already opened (main.py:174)
21:26:17.020 - My_app - ERROR - Dialogue window already opened (main.py:174)
21:26:17.020 - My_app - ERROR - Dialogue window already opened (main.py:174)
21:26:18.020 - My_app - ERROR - Dialogue window already opened (main.py:180)
21:26:18.020 - My_app - ERROR - Dialogue window already opened (main.py:180)
21:26:19.020 - My_app - ERROR - Dialogue window already opened (main.py:180)
21:26:22.020 - My_app - ERROR - Dialogue window already opened (main.py:180)
21:26:22.020 - My_app - ERROR - Dialogue window already opened (main.py:180)
21:26:22.020 - My_app - ERROR - Dialogue window already opened (main.py:180)
21:26:22.020 - My_app - ERROR - Dialogue window already opened (main.py:174)
21:26:22.020 - My_app - ERROR - Dialogue window already opened (main.py:174)
21:26:22.020 - My_app - ERROR - Dialogue window already opened (main.py:174)
21:26:28.020 - My_app - INFO - user is log out (main.py:130)
21:26:31.020 - My_app - INFO - Connected to MySQL by user (main.py:67)
21:26:31.020 - My_app - INFO - Current user is user (main.py:167)
21:26:32.020 - My_app - ERROR - Dialogue window already opened (main.py:180)
21:26:32.020 - My_app - ERROR - Dialogue window already opened (main.py:174)
21:26:33.020 - My_app - ERROR - Dialogue window already opened (main.py:174)
21:26:33.020 - My_app - ERROR - Dialogue window already opened (main.py:174)
21:26:34.020 - My_app - ERROR - Dialogue window already opened (main.py:174)
21:26:35.020 - My_app - INFO - user is log out (main.py:130)
21:26:41.020 - My_app - INFO - Connected to MySQL by user (main.py:67)
21:26:41.020 - My_app - INFO - Current user is user (main.py:167)
21:26:42.020 - My_app - ERROR - Dialogue window already opened (main.py:180)
21:26:42.020 - My_app - ERROR - Dialogue window already opened (main.py:180)
21:26:44.020 - My_app - INFO - user is log out (main.py:130)
21:27:37.020 - My_app - INFO - Connected to MySQL by user (main.py:67)
21:27:37.020 - My_app - INFO - Current user is user (main.py:167)
21:27:39.020 - My_app - INFO - user is log out (main.py:130)
21:27:42.020 - My_app - INFO - Connected to MySQL by user (main.py:67)
21:27:42.020 - My_app - INFO - Current user is user (main.py:167)
21:27:43.020 - My_app - INFO - user is log out (main.py:130)
21:27:52.020 - My_app - INFO - Connected to MySQL by user (main.py:67)
21:27:52.020 - My_app - INFO - Current user is user (main.py:167)
21:30:26.020 - My_app - INFO - user is log out (main.py:130)
21:57:00.020 - My_app - INFO - Connected to MySQL by user (main.py:67)
21:57:00.020 - My_app - INFO - Current user is user (main.py:179)
21:57:08.020 - My_app - INFO - user is log out (main.py:142)
21:58:13.020 - My_app - INFO - Connected to MySQL by user (main.py:67)
21:58:13.020 - My_app - INFO - Current user is user (main.py:180)
21:58:31.020 - My_app - ERROR - 1142 (42000): INSERT command denied to user 'user'@'localhost' for table 'Orders' (main.py:89)
21:58:31.020 - My_app - INFO - Order added in table (main.py:259)
21:58:45.020 - My_app - INFO - user is log out (main.py:143)
22:02:16.020 - My_app - INFO - Connected to MySQL by user (main.py:67)
22:02:16.020 - My_app - INFO - Current user is user (main.py:180)
22:02:20.020 - My_app - ERROR - 1216 (23000): Cannot add or update a child row: a foreign key constraint fails (main.py:89)
22:02:20.020 - My_app - INFO - Order added in table (main.py:259)
22:02:43.020 - My_app - INFO - user is log out (main.py:143)
22:48:47.020 - My_app - INFO - Connected to MySQL by user (main.py:67)
22:48:47.020 - My_app - INFO - Current user is user (main.py:180)
22:57:20.020 - My_app - INFO - Connected to MySQL by user (main.py:67)
22:57:20.020 - My_app - INFO - Current user is user (main.py:180)
22:57:46.020 - My_app - INFO - Order added in table (main.py:259)
22:58:55.020 - My_app - INFO - Order added in table (main.py:259)
23:04:53.020 - My_app - INFO - Connected to MySQL by user (main.py:67)
23:04:53.020 - My_app - INFO - Current user is user (main.py:180)
23:04:59.020 - My_app - ERROR - Error checking id (main.py:27)
23:04:59.020 - My_app - ERROR - Voyage id entered is invalid (main.py:245)
23:05:23.020 - My_app - INFO - user is log out (main.py:143)
23:05:50.020 - My_app - INFO - Connected to MySQL by user (main.py:67)
23:05:50.020 - My_app - INFO - Current user is user (main.py:180)
23:05:55.020 - My_app - ERROR - Error checking id (main.py:27)
23:05:55.020 - My_app - ERROR - Voyage id entered is invalid (main.py:245)
23:06:14.020 - My_app - INFO - Connected to MySQL by user (main.py:67)
23:06:14.020 - My_app - INFO - Current user is user (main.py:180)
23:06:17.020 - My_app - ERROR - Error checking id (main.py:27)
23:06:17.020 - My_app - ERROR - Voyage id entered is invalid (main.py:245)
23:06:35.020 - My_app - INFO - user is log out (main.py:143)
23:09:55.020 - My_app - INFO - Connected to MySQL by user (main.py:67)
23:09:55.020 - My_app - INFO - Current user is user (main.py:180)
23:09:59.020 - My_app - ERROR - Error checking id (main.py:27)
23:09:59.020 - My_app - ERROR - Voyage id entered is invalid (main.py:245)
23:11:14.020 - My_app - ERROR - Error checking id (main.py:27)
23:11:14.020 - My_app - ERROR - Voyage id entered is invalid (main.py:245)
23:11:14.020 - My_app - ERROR - Error checking id (main.py:27)
23:11:14.020 - My_app - ERROR - Voyage id entered is invalid (main.py:245)
23:18:02.020 - My_app - INFO - Connected to MySQL by user (main.py:67)
23:18:02.020 - My_app - INFO - Current user is user (main.py:180)
23:18:06.020 - My_app - ERROR - Error checking id (main.py:27)
23:18:06.020 - My_app - ERROR - Voyage id entered is invalid (main.py:247)
23:18:10.020 - My_app - ERROR - Error checking id (main.py:27)
23:18:10.020 - My_app - ERROR - Voyage id entered is invalid (main.py:247)
23:18:12.020 - My_app - ERROR - Error checking id (main.py:27)
23:18:12.020 - My_app - ERROR - Voyage id entered is invalid (main.py:247)
23:18:13.020 - My_app - ERROR - Error checking id (main.py:27)
23:18:13.020 - My_app - ERROR - Voyage id entered is invalid (main.py:247)
23:18:44.020 - My_app - INFO - Connected to MySQL by user (main.py:67)
23:18:44.020 - My_app - INFO - Current user is user (main.py:180)
23:18:47.020 - My_app - ERROR - Error checking id (main.py:27)
23:18:47.020 - My_app - ERROR - Voyage id entered is invalid (main.py:247)
23:18:49.020 - My_app - ERROR - Error checking id (main.py:27)
23:18:49.020 - My_app - ERROR - Voyage id entered is invalid (main.py:247)
23:18:52.020 - My_app - ERROR - Error checking id (main.py:27)
23:18:52.020 - My_app - ERROR - Voyage id entered is invalid (main.py:247)
23:18:56.020 - My_app - INFO - user is log out (main.py:143)
23:20:46.020 - My_app - INFO - Connected to MySQL by user (main.py:67)
23:20:46.020 - My_app - INFO - Current user is user (main.py:180)
23:20:50.020 - My_app - ERROR - Error checking id (main.py:27)
23:20:50.020 - My_app - ERROR - Voyage id entered is invalid (main.py:247)
23:20:51.020 - My_app - ERROR - Error checking id (main.py:27)
23:20:51.020 - My_app - ERROR - Voyage id entered is invalid (main.py:247)
23:21:01.020 - My_app - ERROR - Error checking id (main.py:27)
23:21:01.020 - My_app - ERROR - Voyage id entered is invalid (main.py:247)
23:21:06.020 - My_app - ERROR - Error checking id (main.py:27)
23:21:06.020 - My_app - ERROR - Voyage id entered is invalid (main.py:247)
23:21:08.020 - My_app - ERROR - Error checking id (main.py:27)
23:21:08.020 - My_app - ERROR - Voyage id entered is invalid (main.py:247)
23:21:17.020 - My_app - INFO - user is log out (main.py:143)
23:22:55.020 - My_app - INFO - Connected to MySQL by user (main.py:67)
23:22:55.020 - My_app - INFO - Current user is user (main.py:180)
23:23:13.020 - My_app - ERROR - Error checking id (main.py:27)
23:23:13.020 - My_app - ERROR - Voyage id entered is invalid (main.py:247)
23:23:16.020 - My_app - ERROR - Error checking id (main.py:27)
23:23:16.020 - My_app - ERROR - Voyage id entered is invalid (main.py:247)
23:23:23.020 - My_app - INFO - user is log out (main.py:143)
23:23:44.020 - My_app - INFO - Connected to MySQL by user (main.py:67)
23:23:44.020 - My_app - INFO - Current user is user (main.py:180)
23:23:48.020 - My_app - ERROR - Error checking id (main.py:27)
23:23:48.020 - My_app - ERROR - Voyage id entered is invalid (main.py:247)
23:23:50.020 - My_app - ERROR - Error checking id (main.py:27)
23:23:50.020 - My_app - ERROR - Voyage id entered is invalid (main.py:247)
23:23:52.020 - My_app - INFO - user is log out (main.py:143)
23:24:39.020 - My_app - ERROR - Not a Phone number entered (main.py:132)
23:24:44.020 - My_app - INFO - Connected to MySQL by user (main.py:67)
23:24:44.020 - My_app - INFO - Current user is user (main.py:180)
23:24:49.020 - My_app - ERROR - Error checking id (main.py:27)
23:24:49.020 - My_app - ERROR - Voyage id entered is invalid (main.py:247)
23:24:50.020 - My_app - ERROR - Error checking id (main.py:27)
23:24:50.020 - My_app - ERROR - Voyage id entered is invalid (main.py:247)
23:25:06.020 - My_app - INFO - user is log out (main.py:143)
23:27:48.020 - My_app - INFO - Connected to MySQL by user (main.py:67)
23:27:48.020 - My_app - INFO - Current user is user (main.py:180)
23:27:52.020 - My_app - ERROR - Error checking id (main.py:27)
23:27:52.020 - My_app - ERROR - Voyage id entered is invalid (main.py:246)
23:27:53.020 - My_app - ERROR - Error checking id (main.py:27)
23:27:53.020 - My_app - ERROR - Voyage id entered is invalid (main.py:246)
23:27:55.020 - My_app - ERROR - Error checking id (main.py:27)
23:27:55.020 - My_app - ERROR - Voyage id entered is invalid (main.py:246)
23:27:56.020 - My_app - ERROR - Error checking id (main.py:27)
23:27:56.020 - My_app - ERROR - Voyage id entered is invalid (main.py:246)
23:27:57.020 - My_app - ERROR - Error checking id (main.py:27)
23:27:57.020 - My_app - ERROR - Voyage id entered is invalid (main.py:246)
23:27:57.020 - My_app - ERROR - Error checking id (main.py:27)
23:27:57.020 - My_app - ERROR - Voyage id entered is invalid (main.py:246)
23:27:58.020 - My_app - ERROR - Error checking id (main.py:27)
23:27:58.020 - My_app - ERROR - Voyage id entered is invalid (main.py:246)
23:28:05.020 - My_app - INFO - user is log out (main.py:143)
